# Generated by Django 4.1.1 on 2022-09-20 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='first Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2022, 9, 20, 8, 17, 47, 562373, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
