# Generated by Django 4.1.1 on 2022-09-27 07:28

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 7, 28, 49, 589335, tzinfo=datetime.timezone.utc)),
        ),
    ]
