# Generated by Django 4.1.1 on 2022-09-27 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_image_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 8, 12, 36, 744896, tzinfo=datetime.timezone.utc)),
        ),
    ]
