# Generated by Django 4.1.1 on 2022-09-27 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 8, 15, 38, 163980, tzinfo=datetime.timezone.utc)),
        ),
    ]
